### ISSUE TITLE
Build failed when building Xspray OSX

### ISSUE THREAD

**Issue by conopt** [meeloo/xspray#7]
Hi Meeloo,

I followed your build instructions, but when I tried to build the target "Xspray OSX", two errors occurred.
1. found cmake binary: using "/usr/local/bin/cmake"
   Traceback (most recent call last):
   File "/Workspace/xspray/lldb/scripts/Xcode/build-llvm.py", line 358, in <module>
     build_llvm_if_needed()
   File "/Workspace/xspray/lldb/scripts/Xcode/build-llvm.py", line 351, in build_llvm_if_needed
     run_cmake_if_needed(ninja_binary_path)
   File "/Workspace/xspray/lldb/scripts/Xcode/build-llvm.py", line 318, in run_cmake_if_needed
     run_cmake(cmake_build_dir, ninja_binary_path)
   File "/Workspace/xspray/lldb/scripts/Xcode/build-llvm.py", line 297, in run_cmake
     command_line = [cmake_binary] + cmake_flags() + [
   File "/Workspace/xspray/lldb/scripts/Xcode/build-llvm.py", line 277, in cmake_flags
     cmake_flags = CMAKE_FLAGS()[lldb_configuration()]
   KeyError: 'BuildAndIntegration'
   Command /bin/sh failed with exit code 1

After I hard coded lldb_configuration() to "Release",
2. debugserver > MachTask.mm > 'pmenergy.h' file not found

OS X version: 10.11.6
Xcode version: 7.3.1
cmake version: 3.5.2

Thanks for your help.

**Comment by tgunr** [comment]
Same problem here, pmenergy nowhere tp be found.

**Comment by rogermc2** [comment]
I also have this problem.
 'pmenergy.h' file not found
Also no pmsample.h.

**Comment by rogermc2** [comment]
pmenergy.h is required by MachTask.mm which seems to be an lldb debugserver file.
Hence an lldb problem?
These files are only required if LLDB_ENERGY is defined.
I undefined LLDB_ENERGY in MachTask.mm which allowed the building to continue.

**Comment by rogermc2** [comment]
This issue is now addressed by Issue #8 so, probably, can be closed.
